<?php

declare(strict_types=1);

/**
 * The same short story in every locale the package maps.
 * Used to visually check shaping, joining, and fallback fonts.
 *
 * @return list<array{id: string, name: string, native: string, dir: string, font: string, title: string, paragraphs: list<string>}>
 */
return [
    [
        'id' => 'en',
        'name' => 'English',
        'native' => 'English',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'The Book by the River',
        'paragraphs' => [
            'One quiet morning a child named Noor walked along the river behind the old market. The water moved slowly, as if it were thinking. Between two wet stones they found a book with no title on the cover. When the first page opened, it spoke in their own language. The next page changed. Letters rearranged themselves like birds looking for a new tree.',
            'Noor sat under a mango tree and read until the sun stood high. A merchant from the spice lane asked what they were reading. “A story that refuses to stay in one tongue,” Noor said. The merchant laughed, then grew still when he heard his grandmother’s words rise from the paper as if she were sitting beside them.',
            'They carried the book through the city. In the tea stall a student heard a familiar greeting and smiled. At the station a traveler closed their eyes and listened. In the park an old woman finished a sentence before Noor did, because the story already lived in her memory.',
            'By evening the last page was almost blank. Only one line remained: Write the next page in the language you love. Noor wrote slowly. The ink smelled like rain after heat. When they closed the book, the river sounded like many voices agreeing to listen.',
            'That night the market lights looked like punctuation scattered across the dark. Noor understood something simple and large: a story is not finished when the words end. It is finished when another person can hear it, and answer.',
        ],
    ],
    [
        'id' => 'bn',
        'name' => 'Bengali',
        'native' => 'বাংলা',
        'dir' => 'ltr',
        'font' => 'AI-Borno',
        'title' => 'নদীর পাশে পাওয়া বই',
        'paragraphs' => [
            'এক শান্ত সকালে নূর নামের একটি শিশু পুরনো বাজারের পেছনের নদীর ধার দিয়ে হেঁটে যাচ্ছিল। জল আস্তে আস্তে চলছিল, যেন সে চিন্তা করছে। দুটি ভেজা পাথরের মাঝখানে তারা একটি বই পেল, যার মলাটে কোনো নাম ছিল না। প্রথম পৃষ্ঠা খুললে সে তাদের নিজের ভাষায় কথা বলল। পরের পৃষ্ঠা বদলে গেল। অক্ষরগুলো পাখির মতো নতুন গাছ খুঁজে সরে গেল।',
            'নূর আমগাছের নিচে বসে পড়তে লাগল, যতক্ষণ না রোদ মাথার উপর এসে দাঁড়ায়। মশলার গলির এক বণিক জিজ্ঞেস করল তারা কী পড়ছে। নূর বলল, “এমন এক গল্প যা এক ভাষায় থাকতে চায় না।” বণিক হাসলেন, তারপর চুপ হয়ে গেলেন—কাগজ থেকে তাঁর দাদির কণ্ঠ যেন উঠে এল, যেন তিনি পাশেই বসে আছেন।',
            'তারা বইটি নিয়ে শহর ঘুরল। চায়ের দোকানে এক শিক্ষার্থী চেনা অভিবাদন শুনে হাসল। স্টেশনে এক যাত্রী চোখ বন্ধ করে শুনল। পার্কে এক বৃদ্ধা নূরের আগেই বাক্য শেষ করলেন, কারণ গল্পটি আগে থেকেই তাঁর স্মৃতিতে বাস করছিল।',
            'সন্ধ্যায় শেষ পৃষ্ঠা প্রায় খালি। শুধু এক লাইন ছিল: তুমি যে ভাষা ভালোবাসো, সেই ভাষায় পরের পৃষ্ঠা লেখো। নূর ধীরে ধীরে লিখল। কালিতে বৃষ্টির গন্ধ। বই বন্ধ করলে নদী শোনাল হাজার কণ্ঠ, যেন সবাই শুনতে রাজি।',
            'সে রাতে বাজারের আলোগুলো অন্ধকারে বিরামচিহ্নের মতো লাগল। নূর একটি সরল ও বড় কথা বুঝল: শব্দ শেষ হলে গল্প শেষ হয় না। গল্প শেষ হয় তখন, যখন অন্য কেউ সেটি শুনতে পারে এবং উত্তর দিতে পারে।',
        ],
    ],
    [
        'id' => 'hi',
        'name' => 'Hindi',
        'native' => 'हिन्दी',
        'dir' => 'ltr',
        'font' => 'Noto Sans Devanagari',
        'title' => 'नदी के किनारे मिली किताब',
        'paragraphs' => [
            'एक शांत सुबह नूर नाम का बच्चा पुराने बाज़ार के पीछे नदी के किनारे चल रहा था। पानी धीरे बह रहा था, जैसे वह सोच रहा हो। दो गीले पत्थरों के बीच उन्हें एक किताब मिली, जिसके आवरण पर कोई शीर्षक नहीं था। पहला पृष्ठ खुला तो वह उनकी अपनी भाषा में बोली। अगला पृष्ठ बदल गया। अक्षर पक्षियों की तरह नया पेड़ खोजते हुए सरक गए।',
            'नूर आम के पेड़ के नीचे बैठकर पढ़ता रहा, जब तक सूरज सिर पर न आ गया। मसाले की गली के एक व्यापारी ने पूछा कि वे क्या पढ़ रहे हैं। नूर ने कहा, “एक ऐसी कहानी जो एक भाषा में नहीं रहना चाहती।” व्यापारी हँसा, फिर चुप हो गया—कागज़ से उसकी दादी की आवाज़ उठी, जैसे वह पास बैठी हों।',
            'वे किताब लेकर शहर घूमे। चाय की दुकान में एक विद्यार्थी ने परिचित अभिवादन सुना और मुस्कराया। स्टेशन पर एक यात्री ने आँखें बंद कर लीं। पार्क में एक वृद्धा ने नूर से पहले वाक्य पूरा कर दिया, क्योंकि कहानी पहले से उनकी स्मृति में बसती थी।',
            'शाम तक अंतिम पृष्ठ लगभग खाली था। केवल एक पंक्ति बची थी: जिस भाषा से तुम प्रेम करते हो, उसी में अगला पृष्ठ लिखो। नूर ने धीरे लिखा। स्याही में बारिश जैसी गंध थी। किताब बंद करते ही नदी हज़ारों स्वरों जैसी लगने लगी, मानो सब सुनने को तैयार हों।',
            'उस रात बाज़ार की बत्तियाँ अंधकार में विराम चिह्नों जैसी दिखीं। नूर ने एक सरल और बड़ी बात समझी: शब्द समाप्त होने पर कहानी समाप्त नहीं होती। कहानी तब पूरी होती है जब कोई और उसे सुन सके और उत्तर दे सके।',
        ],
    ],
    [
        'id' => 'ar',
        'name' => 'Arabic',
        'native' => 'العربية',
        'dir' => 'rtl',
        'font' => 'Noto Sans Arabic',
        'title' => 'الكتاب على ضفة النهر',
        'paragraphs' => [
            'في صباح هادئ مشى طفل اسمه نور على ضفة النهر خلف السوق القديم. كان الماء يسير ببطء كأنّه يفكّر. بين حجرين مبلولين وجد كتاباً بلا عنوان على الغلاف. عندما فُتحت الصفحة الأولى تكلّمت بلغته. ثم تبدّلت الصفحة التالية. تحرّكت الحروف كما تبحث الطيور عن شجرة جديدة.',
            'جلس نور تحت شجرة مانجو وقرأ حتى صار الشمس فوق رأسه. سأله تاجر من زقاق التوابل عمّا يقرأ. قال نور: «قصّة ترفض أن تبقى في لسان واحد.» ضحك التاجر ثم سكت حين سمع كلام جدّته يصعد من الورق كأنّها تجلس إلى جواره.',
            'حمل الكتاب في المدينة. في دكّان الشاي سمع طالب تحيّة مألوفة وابتسم. في المحطة أغمض مسافر عينيه واستمع. في الحديقة أكملت امرأة عجوز الجملة قبل نور، لأن القصّة كانت تسكن ذاكرتها من قبل.',
            'عند المساء كانت الصفحة الأخيرة شبه فارغة. بقي سطر واحد: اكتب الصفحة التالية باللغة التي تحبّها. كتب نور ببطء. فاحت الحبر برائحة المطر بعد الحرّ. وعندما أغلق الكتاب بدا النهر كألف صوت يتّفق على الإنصات.',
            'في تلك الليلة بدت أضواء السوق كعلامات ترقيم فوق الظلام. فهم نور أمراً بسيطاً وكبيراً: لا تنتهي القصّة حين تنتهي الكلمات. تنتهي حين يستطيع شخص آخر أن يسمعها ويجيب.',
        ],
    ],
    [
        'id' => 'ur',
        'name' => 'Urdu',
        'native' => 'اردو',
        'dir' => 'rtl',
        'font' => 'Noto Sans Arabic',
        'title' => 'دریا کے کنارے ملی کتاب',
        'paragraphs' => [
            'ایک خاموش صبح نور نام کا بچہ پرانے بازار کے پیچھے دریا کے کنارے چل رہا تھا۔ پانی آہستہ بہہ رہا تھا، جیسے سوچ رہا ہو۔ دو گیلے پتھروں کے بیچ ایک کتاب ملی جس کے سرورق پر کوئی عنوان نہیں تھا۔ پہلا صفحہ کھلا تو وہ ان کی اپنی زبان میں بولا۔ اگلا صفحہ بدل گیا۔ حروف پرندوں کی طرح نیا درخت ڈھونڈتے ہوئے سرک گئے۔',
            'نور آم کے درخت تلے بیٹھ کر پڑھتا رہا یہاں تک کہ سورج سر پر آ گیا۔ مصالحے کی گلی کے ایک سوداگر نے پوچھا وہ کیا پڑھ رہے ہیں۔ نور نے کہا، «ایک ایسی کہانی جو ایک زبان میں رہنا نہیں چاہتی۔» سوداگر ہنسا، پھر خاموش ہو گیا—کاغذ سے اس کی دادی کی آواز اٹھی جیسے وہ پاس بیٹھی ہوں۔',
            'وہ کتاب لے کر شہر گھومے۔ چائے کی دکان پر ایک طالب علم نے جانا پہچانا سلام سنا اور مسکرایا۔ اسٹیشن پر ایک مسافر نے آنکھیں بند کر لیں۔ پارک میں ایک بوڑھی عورت نے نور سے پہلے جملہ پورا کر دیا، کیونکہ کہانی پہلے سے اس کی یاد میں بس رہی تھی۔',
            'شام تک آخری صفحہ تقریباً خالی تھا۔ صرف ایک سطر رہ گئی: جس زبان سے تم محبت کرتے ہو اسی میں اگلا صفحہ لکھو۔ نور نے آہستہ لکھا۔ روشنائی میں بارش کی خوشبو تھی۔ کتاب بند کرتے ہی دریا ہزاروں آوازوں جیسا لگا، جیسے سب سننے کو تیار ہوں۔',
            'اس رات بازار کی روشنیاں اندھیرے میں رموز اوقاف کی طرح دکھائی دیں۔ نور نے ایک سادہ اور بڑی بات سمجھی: الفاظ ختم ہونے سے کہانی ختم نہیں ہوتی۔ کہانی تب مکمل ہوتی ہے جب کوئی اور اسے سن سکے اور جواب دے سکے۔',
        ],
    ],
    [
        'id' => 'fa',
        'name' => 'Persian',
        'native' => 'فارسی',
        'dir' => 'rtl',
        'font' => 'Noto Sans Arabic',
        'title' => 'کتاب کنار رودخانه',
        'paragraphs' => [
            'در یک صبح آرام کودکی به نام نور کنار رودخانه پشت بازار کهنه راه می‌رفت. آب آهسته می‌رفت، انگار فکر می‌کرد. میان دو سنگ خیس کتابی یافت که روی جلدش عنوانی نبود. صفحهٔ نخست که باز شد به زبان خودش سخن گفت. صفحهٔ بعد عوض شد. حرف‌ها مانند پرندگانی که درخت تازه‌ای می‌جویند جابه‌جا شدند.',
            'نور زیر درخت انبه نشست و خواند تا آفتاب بالای سر آمد. بازرگانی از کوچهٔ ادویه پرسید چه می‌خوانی. نور گفت: «داستانی که نمی‌خواهد در یک زبان بماند.» بازرگان خندید و بعد ساکت شد، چون صدای مادربزرگش از کاغذ برخاست، چنان‌که کنارشان نشسته باشد.',
            'کتاب را در شهر گرداندند. در قهوه‌خانه دانشجویی سلام آشنا شنید و لبخند زد. در ایستگاه مسافری چشم بست و گوش داد. در بوستان پیرزنی جمله را پیش از نور تمام کرد، زیرا داستان از پیش در حافظه‌اش زندگی می‌کرد.',
            'شامگاه صفحهٔ آخر تقریباً خالی بود. فقط یک سطر مانده بود: صفحهٔ بعد را به زبانی بنویس که دوستش داری. نور آهسته نوشت. جوهر بوی باران پس از گرما می‌داد. چون کتاب را بست، رودخانه مانند هزار صدا به گوش رسید که همه توافق کرده بودند گوش کنند.',
            'آن شب چراغ‌های بازار مانند نشانه‌های سجاوندی روی تاریکی دیده می‌شد. نور چیزی ساده و بزرگ فهمید: داستان وقتی واژه‌ها تمام می‌شوند تمام نمی‌شود. تمام می‌شود وقتی کس دیگری بتواند آن را بشنود و پاسخ دهد.',
        ],
    ],
    [
        'id' => 'he',
        'name' => 'Hebrew',
        'native' => 'עברית',
        'dir' => 'rtl',
        'font' => 'Noto Sans Hebrew',
        'title' => 'הספר על גדת הנהר',
        'paragraphs' => [
            'בבוקר שקט הלך ילד ושמו נור לאורך הנהר מאחורי השוק הישן. המים זרמו לאט, כאילו הם חושבים. בין שתי אבנים רטובות מצא ספר בלי שם על הכריכה. כשנפתח העמוד הראשון הוא דיבר בשפתו. העמוד הבא השתנה. האותיות זזו כמו ציפורים שמחפשות עץ חדש.',
            'נור ישב תחת עץ מנגו וקרא עד שהשמש עמדה מעל ראשו. סוחר מסמטת התבלינים שאל מה הוא קורא. נור אמר: «סיפור שמסרב להישאר בלשון אחת.» הסוחר צחק ואז השתתק כששמע את דברי סבתו עולים מן הנייר כאילו היא יושבת לידם.',
            'הם נשאו את הספר בעיר. בדוכן התה שמע סטודנט ברכה מוכרת וחייך. בתחנה נוסע עצם עיניים והקשיב. בפארק אישה זקנה סיימה משפט לפני נור, כי הסיפור כבר חי בזיכרונה.',
            'לערב העמוד האחרון היה כמעט ריק. נשארה רק שורה אחת: כתוב את העמוד הבא בשפה שאתה אוהב. נור כתב לאט. לדיו היה ריח של גשם אחרי חום. כשסגר את הספר, הנהר נשמע כמו אלף קולות שמסכימים להקשיב.',
            'באותו לילה נראו אורות השוק כמו סימני פיסוק על החשכה. נור הבין דבר פשוט וגדול: הסיפור אינו נגמר כשהמילים נגמרות. הוא נגמר כאשר אדם אחר יכול לשמוע ולענות.',
        ],
    ],
    [
        'id' => 'th',
        'name' => 'Thai',
        'native' => 'ไทย',
        'dir' => 'ltr',
        'font' => 'Noto Sans Thai',
        'title' => 'หนังสือริมแม่น้ำ',
        'paragraphs' => [
            'เช้าอันสงบวันหนึ่ง เด็กชื่อ นูร์ เดินไปตามริมแม่น้ำด้านหลังตลาดเก่า น้ำไหลช้า ราวกับกำลังคิด ระหว่างหินเปียกสองก้อน พวกเขาพบหนังสือที่ปกไม่มีชื่อ เมื่อเปิดหน้าแรก มันพูดเป็นภาษาของเขา หน้าถัดไปเปลี่ยน ตัวอักษรขยับตัวเหมือนนกที่กำลังหาต้นไม้ใหม่',
            'นูร์นั่งใต้ต้นมะม่วงอ่านจนพระอาทิตย์อยู่เหนือศีรษะ พ่อค้าจากตรอกเครื่องเทศถามว่าอ่านอะไร นูร์ตอบว่า “เรื่องที่ไม่ยอมอยู่ในภาษาเดียว” พ่อค้าหัวเราะ แล้วเงียบเมื่อได้ยินคำของยายลอยขึ้นจากกระดาษ ราวกับท่านนั่งอยู่ข้าง ๆ',
            'พวกเขาพาหนังสือเดินทั่วเมือง ที่ร้านชา นักเรียนได้ยินคำทักทายที่คุ้นเคยแล้วยิ้ม ที่สถานี คนเดินทางหลับตาฟัง ในสวน สตรีสูงวัยพูดจบประโยคก่อนนูร์ เพราะเรื่องนั้นอาศัยในความทรงจำของท่านอยู่แล้ว',
            'ยามเย็น หน้าสุดท้ายเกือบว่าง เหลือเพียงบรรทัดเดียว จงเขียนหน้าถัดไปในภาษาที่เธอรัก นูร์เขียนอย่างช้า ๆ หมึกมีกลิ่นฝนหลังความร้อน เมื่อปิดหนังสือ แม่น้ำฟังดูเหมือนเสียงนับพันที่ตกลงจะตั้งใจฟัง',
            'คืนนั้น ไฟตลาดดูเหมือนเครื่องหมายวรรคตอนบนความมืด นูร์เข้าใจสิ่งที่เรียบง่ายและยิ่งใหญ่ เรื่องเล่าไม่จบเมื่อคำหมด เรื่องเล่าจบเมื่อคนอื่นได้ยินและตอบได้',
        ],
    ],
    [
        'id' => 'ru',
        'name' => 'Russian',
        'native' => 'Русский',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Книга у реки',
        'paragraphs' => [
            'Тихим утром ребёнок по имени Нур шёл вдоль реки за старым рынком. Вода двигалась медленно, словно думала. Между двумя мокрыми камнями нашлась книга без названия на обложке. Первая страница заговорила на родном языке. Следующая страница изменилась. Буквы перестроились, как птицы, что ищут новое дерево.',
            'Нур сел под манговым деревом и читал, пока солнце не встало над головой. Купец из переулка специй спросил, что они читают. «Историю, которая не хочет жить на одном языке», — сказал Нур. Купец рассмеялся и замолчал, когда с бумаги поднялся голос бабушки, будто она сидела рядом.',
            'Они понесли книгу по городу. В чайной студент услышал знакомое приветствие и улыбнулся. На вокзале путник закрыл глаза и слушал. В парке старушка закончила фразу раньше Нура, потому что история уже жила в её памяти.',
            'К вечеру последняя страница была почти пуста. Осталась одна строка: напиши следующую страницу на языке, который любишь. Нур писал медленно. Чернила пахли дождём после жары. Когда книгу закрыли, река зазвучала тысячью голосов, готовых слушать.',
            'Ночью огни рынка были похожи на знаки препинания в темноте. Нур понял простую и большую мысль: история не кончается, когда кончаются слова. Она кончается, когда другой человек может её услышать и ответить.',
        ],
    ],
    [
        'id' => 'uk',
        'name' => 'Ukrainian',
        'native' => 'Українська',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Книга біля річки',
        'paragraphs' => [
            'Тихого ранку дитина на ім’я Нур ішла вздовж річки за старим базаром. Вода рухалася повільно, наче думала. Між двома мокрими каменями знайшлася книжка без назви на обкладинці. Перша сторінка заговорила рідною мовою. Наступна сторінка змінилася. Літери перешикувалися, як птахи, що шукають нове дерево.',
            'Нур сів під манговим деревом і читав, доки сонце не стало над головою. Купець зі спецевої вулички запитав, що вони читають. «Історію, яка не хоче лишатися однією мовою», — сказав Нур. Купець засміявся й замовк, коли з паперу піднявся голос бабусі, ніби вона сиділа поруч.',
            'Вони понесли книжку містом. У чайній студент почув знайоме вітання і всміхнувся. На вокзалі мандрівник заплющив очі й слухав. У парку літня жінка закінчила речення раніше за Нура, бо історія вже жила в її пам’яті.',
            'Надвечір остання сторінка була майже порожня. Лишився один рядок: напиши наступну сторінку мовою, яку любиш. Нур писав повільно. Чорнило пахло дощем після спеки. Коли книжку закрили, річка залунала тисячею голосів, згодних слухати.',
            'Тієї ночі вогні базару були схожі на розділові знаки в темряві. Нур зрозумів просту й велику річ: історія не кінчається, коли кінчаються слова. Вона кінчається, коли інша людина може її почути й відповісти.',
        ],
    ],
    [
        'id' => 'el',
        'name' => 'Greek',
        'native' => 'Ελληνικά',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Το βιβλίο δίπλα στο ποτάμι',
        'paragraphs' => [
            'Ένα ήσυχο πρωί ένα παιδί που το έλεγαν Νουρ περπατούσε δίπλα στο ποτάμι πίσω από την παλιά αγορά. Το νερό κυλούσε αργά, σαν να σκεφτόταν. Ανάμεσα σε δύο βρεγμένες πέτρες βρήκαν ένα βιβλίο χωρίς τίτλο στο εξώφυλλο. Όταν άνοιξε η πρώτη σελίδα, μίλησε στη γλώσσα τους. Η επόμενη σελίδα άλλαξε. Τα γράμματα μετακινήθηκαν σαν πουλιά που ψάχνουν νέο δέντρο.',
            'Ο Νουρ κάθισε κάτω από μια μάνγκο και διάβαζε ώσπου ο ήλιος στάθηκε πάνω από το κεφάλι. Ένας έμπορος από το σοκάκι των μπαχαρικών ρώτησε τι διαβάζουν. «Μια ιστορία που αρνείται να μείνει σε μία γλώσσα», είπε ο Νουρ. Ο έμπορος γέλασε και μετά σώπασε όταν άκουσε τη φωνή της γιαγιάς του να σηκώνεται από το χαρτί.',
            'Πήραν το βιβλίο στην πόλη. Στο τσάι ένας φοιτητής άκουσε έναν γνώριμο χαιρετισμό και χαμογέλασε. Στον σταθμό ένας ταξιδιώτης έκλεισε τα μάτια. Στο πάρκο μια ηλικιωμένη τελείωσε την πρόταση πριν από τον Νουρ, γιατί η ιστορία ζούσε ήδη στη μνήμη της.',
            'Το βράδυ η τελευταία σελίδα ήταν σχεδόν κενή. Έμεινε μία γραμμή: γράψε την επόμενη σελίδα στη γλώσσα που αγαπάς. Ο Νουρ έγραψε αργά. Το μελάνι μύριζε βροχή μετά τη ζέστη. Όταν έκλεισαν το βιβλίο, το ποτάμι ακουγόταν σαν χίλιες φωνές που συμφωνούσαν να ακούσουν.',
            'Εκείνη τη νύχτα τα φώτα της αγοράς έμοιαζαν με σημεία στίξης στο σκοτάδι. Ο Νουρ κατάλαβε κάτι απλό και μεγάλο: η ιστορία δεν τελειώνει όταν τελειώνουν οι λέξεις. Τελειώνει όταν κάποιος άλλος μπορεί να την ακούσει και να απαντήσει.',
        ],
    ],
    [
        'id' => 'es',
        'name' => 'Spanish',
        'native' => 'Español',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'El libro junto al río',
        'paragraphs' => [
            'Una mañana quieta, un niño llamado Noor caminaba junto al río detrás del mercado viejo. El agua se movía despacio, como si pensara. Entre dos piedras mojadas hallaron un libro sin título en la tapa. Al abrirse la primera página, habló en su propia lengua. La página siguiente cambió. Las letras se reordenaron como pájaros que buscan un árbol nuevo.',
            'Noor se sentó bajo un mango y leyó hasta que el sol quedó alto. Un mercader del callejón de las especias preguntó qué leían. «Una historia que se niega a quedarse en una sola lengua», dijo Noor. El mercader rió y luego calló cuando oyó las palabras de su abuela subir del papel, como si estuviera sentada a su lado.',
            'Llevaron el libro por la ciudad. En el puesto de té un estudiante oyó un saludo conocido y sonrió. En la estación un viajero cerró los ojos y escuchó. En el parque una anciana terminó la frase antes que Noor, porque la historia ya vivía en su memoria.',
            'Al anochecer la última página estaba casi en blanco. Quedaba una sola línea: escribe la página siguiente en la lengua que amas. Noor escribió despacio. La tinta olía a lluvia después del calor. Al cerrar el libro, el río sonó como mil voces de acuerdo en escuchar.',
            'Esa noche las luces del mercado parecían signos de puntuación sobre la oscuridad. Noor entendió algo simple y grande: una historia no termina cuando acaban las palabras. Termina cuando otra persona puede oírla y responder.',
        ],
    ],
    [
        'id' => 'fr',
        'name' => 'French',
        'native' => 'Français',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Le livre au bord de la rivière',
        'paragraphs' => [
            'Un matin calme, un enfant nommé Noor marchait le long de la rivière derrière le vieux marché. L’eau avançait lentement, comme si elle pensait. Entre deux pierres mouillées, ils trouvèrent un livre sans titre sur la couverture. Quand la première page s’ouvrit, elle parla dans leur langue. La page suivante changea. Les lettres se réarrangèrent comme des oiseaux cherchant un nouvel arbre.',
            'Noor s’assit sous un manguier et lut jusqu’à ce que le soleil soit haut. Un marchand de la ruelle des épices demanda ce qu’ils lisaient. « Une histoire qui refuse de rester dans une seule langue », dit Noor. Le marchand rit, puis se tut en entendant la voix de sa grand-mère monter du papier, comme si elle était assise à côté d’eux.',
            'Ils portèrent le livre à travers la ville. Au salon de thé, un étudiant entendit une salutation familière et sourit. À la gare, un voyageur ferma les yeux et écouta. Au parc, une vieille femme acheva la phrase avant Noor, parce que l’histoire vivait déjà dans sa mémoire.',
            'Le soir, la dernière page était presque vide. Il restait une ligne : écris la page suivante dans la langue que tu aimes. Noor écrivit lentement. L’encre sentait la pluie après la chaleur. En refermant le livre, la rivière sembla mille voix d’accord pour écouter.',
            'Cette nuit-là, les lumières du marché ressemblaient à de la ponctuation sur l’obscurité. Noor comprit une chose simple et grande : une histoire n’est pas finie quand les mots s’arrêtent. Elle est finie quand quelqu’un d’autre peut l’entendre et répondre.',
        ],
    ],
    [
        'id' => 'de',
        'name' => 'German',
        'native' => 'Deutsch',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Das Buch am Fluss',
        'paragraphs' => [
            'An einem stillen Morgen ging ein Kind namens Noor am Fluss hinter dem alten Markt entlang. Das Wasser bewegte sich langsam, als dächte es nach. Zwischen zwei nassen Steinen fanden sie ein Buch ohne Titel auf dem Einband. Als sich die erste Seite öffnete, sprach sie in ihrer Sprache. Die nächste Seite wechselte. Buchstaben rückten sich zurecht wie Vögel, die einen neuen Baum suchen.',
            'Noor saß unter einem Mangobaum und las, bis die Sonne hoch stand. Ein Händler aus der Gewürzgasse fragte, was sie läsen. „Eine Geschichte, die in keiner einzelnen Sprache bleiben will“, sagte Noor. Der Händler lachte und wurde still, als er die Stimme seiner Großmutter vom Papier aufsteigen hörte, als säße sie neben ihnen.',
            'Sie trugen das Buch durch die Stadt. Im Teeladen hörte ein Student einen vertrauten Gruß und lächelte. Am Bahnhof schloss ein Reisender die Augen und lauschte. Im Park beendete eine alte Frau den Satz vor Noor, weil die Geschichte schon in ihrer Erinnerung lebte.',
            'Am Abend war die letzte Seite fast leer. Nur eine Zeile blieb: Schreibe die nächste Seite in der Sprache, die du liebst. Noor schrieb langsam. Die Tinte roch nach Regen nach der Hitze. Als sie das Buch schlossen, klang der Fluss wie tausend Stimmen, die sich einig waren zu hören.',
            'In jener Nacht wirkten die Marktlichter wie Satzzeichen auf der Dunkelheit. Noor verstand etwas Einfaches und Großes: Eine Geschichte ist nicht zu Ende, wenn die Wörter enden. Sie ist zu Ende, wenn ein anderer Mensch sie hören und antworten kann.',
        ],
    ],
    [
        'id' => 'pt',
        'name' => 'Portuguese',
        'native' => 'Português',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'O livro à beira do rio',
        'paragraphs' => [
            'Numa manhã quieta, uma criança chamada Noor caminhava à beira do rio atrás do mercado velho. A água avançava devagar, como se pensasse. Entre duas pedras molhadas acharam um livro sem título na capa. Quando a primeira página se abriu, falou na língua deles. A página seguinte mudou. As letras reorganizaram-se como pássaros à procura de uma árvore nova.',
            'Noor sentou-se debaixo de uma mangueira e leu até o sol ficar alto. Um mercador do beco das especiarias perguntou o que liam. «Uma história que se recusa a ficar numa só língua», disse Noor. O mercador riu e depois calou-se ao ouvir a voz da avó subir do papel, como se estivesse sentada ao lado.',
            'Levaram o livro pela cidade. No chá, um estudante ouviu uma saudação conhecida e sorriu. Na estação, um viajante fechou os olhos e escutou. No parque, uma senhora idosa terminou a frase antes de Noor, porque a história já vivia na memória dela.',
            'Ao anoitecer, a última página estava quase em branco. Restava uma linha: escreve a página seguinte na língua que amas. Noor escreveu devagar. A tinta cheirava a chuva depois do calor. Ao fechar o livro, o rio soou como mil vozes de acordo em escutar.',
            'Naquela noite, as luzes do mercado pareciam pontuação sobre a escuridão. Noor entendeu uma coisa simples e grande: uma história não acaba quando as palavras acabam. Acaba quando outra pessoa pode ouvi-la e responder.',
        ],
    ],
    [
        'id' => 'tr',
        'name' => 'Turkish',
        'native' => 'Türkçe',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Nehir kenarındaki kitap',
        'paragraphs' => [
            'Sessiz bir sabah Noor adlı bir çocuk eski pazarın arkasındaki nehir boyunca yürüdü. Su yavaş ilerliyordu, düşünüyormuş gibi. İki ıslak taşın arasında kapağında adı olmayan bir kitap buldular. İlk sayfa açılınca kendi dillerinde konuştu. Sonraki sayfa değişti. Harfler yeni bir ağaç arayan kuşlar gibi yer değiştirdi.',
            'Noor bir mango ağacının altına oturdu ve güneş tepedeyken okumayı sürdürdü. Baharat sokağından bir tüccar ne okuduklarını sordu. Noor dedi ki: “Tek dilde kalmayı reddeden bir hikâye.” Tüccar güldü, sonra sustu; kâğıttan ninesinin sesi yükseldi, yanında oturuyormuş gibi.',
            'Kitabı şehirde gezdirdiler. Çayhanede bir öğrenci tanıdık bir selam duydu ve gülümsedi. İstasyonda bir yolcu gözlerini kapadı ve dinledi. Parkta yaşlı bir kadın cümleyi Noor’dan önce bitirdi, çünkü hikâye çoktan onun belleğinde yaşıyordu.',
            'Akşama doğru son sayfa neredeyse boştu. Tek bir satır kalmıştı: bir sonraki sayfayı sevdiğin dilde yaz. Noor yavaş yazdı. Mürekkep sıcaktan sonra yağan yağmur gibi kokuyordu. Kitabı kapayınca nehir, dinlemeyi kabul etmiş bin ses gibi duyuldu.',
            'O gece pazar ışıkları karanlığın üstünde noktalama işaretleri gibi duruyordu. Noor yalın ve büyük bir şeyi anladı: sözcükler bitince hikâye bitmez. Hikâye, başka biri onu duyup yanıtlayabildiğinde biter.',
        ],
    ],
    [
        'id' => 'vi',
        'name' => 'Vietnamese',
        'native' => 'Tiếng Việt',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Cuốn sách bên sông',
        'paragraphs' => [
            'Một sáng yên ả, đứa trẻ tên Noor đi dọc bờ sông phía sau khu chợ cũ. Nước chảy chậm như đang nghĩ. Giữa hai hòn đá ướt, chúng tìm thấy một cuốn sách không có tựa trên bìa. Trang đầu mở ra thì nói bằng chính ngôn ngữ của chúng. Trang sau đổi. Chữ cái sắp xếp lại như chim tìm một cái cây mới.',
            'Noor ngồi dưới cây xoài và đọc đến khi mặt trời đứng trên đầu. Một người buôn từ con hẻm gia vị hỏi chúng đang đọc gì. Noor nói: “Một câu chuyện không chịu ở trong một thứ tiếng.” Người buôn cười rồi im, khi nghe giọng bà mình trỗi lên từ giấy, như bà đang ngồi cạnh.',
            'Chúng mang sách đi khắp thành phố. Ở quán trà, một sinh viên nghe lời chào quen thuộc và mỉm cười. Ở nhà ga, một người đi đường nhắm mắt lắng nghe. Trong công viên, một bà cụ nói hết câu trước Noor, vì câu chuyện đã sống trong trí nhớ bà.',
            'Chiều tối, trang cuối gần như trống. Chỉ còn một dòng: hãy viết trang tiếp theo bằng ngôn ngữ bạn yêu. Noor viết chậm. Mực có mùi mưa sau nắng. Khi đóng sách, dòng sông nghe như nghìn giọng đồng ý lắng nghe.',
            'Đêm ấy đèn chợ giống dấu câu rải trên bóng tối. Noor hiểu một điều đơn giản và lớn: câu chuyện không kết thúc khi lời kết thúc. Nó kết thúc khi người khác nghe được và trả lời được.',
        ],
    ],
    [
        'id' => 'id',
        'name' => 'Indonesian',
        'native' => 'Bahasa Indonesia',
        'dir' => 'ltr',
        'font' => 'Noto Sans',
        'title' => 'Buku di tepi sungai',
        'paragraphs' => [
            'Pada pagi yang sunyi, seorang anak bernama Noor berjalan di tepi sungai di belakang pasar lama. Air bergerak pelan, seolah sedang berpikir. Di antara dua batu basah mereka menemukan sebuah buku tanpa judul di sampulnya. Ketika halaman pertama terbuka, buku itu berbicara dalam bahasa mereka. Halaman berikutnya berubah. Huruf-huruf berpindah seperti burung yang mencari pohon baru.',
            'Noor duduk di bawah pohon mangga dan membaca sampai matahari tinggi. Seorang pedagang dari lorong rempah bertanya apa yang mereka baca. “Sebuah cerita yang menolak tinggal dalam satu lidah,” kata Noor. Pedagang itu tertawa, lalu diam ketika mendengar suara neneknya naik dari kertas, seolah ia duduk di samping mereka.',
            'Mereka membawa buku itu keliling kota. Di warung teh seorang mahasiswa mendengar salam yang dikenal dan tersenyum. Di stasiun seorang musafir memejamkan mata dan mendengar. Di taman seorang nenek menyelesaikan kalimat sebelum Noor, karena cerita itu sudah hidup dalam ingatannya.',
            'Menjelang malam halaman terakhir hampir kosong. Tinggal satu baris: tulislah halaman berikutnya dalam bahasa yang kamu cintai. Noor menulis pelan. Tintanya berbau hujan setelah panas. Ketika buku ditutup, sungai terdengar seperti seribu suara yang setuju untuk mendengar.',
            'Malam itu lampu pasar tampak seperti tanda baca di atas gelap. Noor memahami hal yang sederhana dan besar: cerita tidak selesai ketika kata-kata habis. Cerita selesai ketika orang lain dapat mendengarnya dan menjawab.',
        ],
    ],
    [
        'id' => 'ta',
        'name' => 'Tamil',
        'native' => 'தமிழ்',
        'dir' => 'ltr',
        'font' => 'Noto Sans Tamil',
        'title' => 'ஆற்றங்கரையில் கிடைத்த புத்தகம்',
        'paragraphs' => [
            'ஒரு அமைதியான காலையில் நூர் என்ற குழந்தை பழைய சந்தையின் பின்னால் ஆற்றங்கரையில் நடந்தது. நீர் மெதுவாக ஓடியது, சிந்திப்பது போல. இரண்டு ஈரக் கற்களுக்கு இடையே அட்டைப்பில் பெயரற்ற ஒரு புத்தகம் கிடைத்தது. முதல் பக்கம் திறந்ததும் அது அவர்களின் மொழியில் பேசியது. அடுத்த பக்கம் மாறியது. எழுத்துகள் புதிய மரத்தைத் தேடும் பறவைகள் போல் நகர்ந்தன.',
            'நூர் மாமரத்தின் கீழ் அமர்ந்து சூரியன் உச்சத்தில் நிற்கும் வரை படித்தார். மசாலா சந்தையின் ஒரு வணிகர் என்ன படிக்கிறீர்கள் என்று கேட்டார். நூர் சொன்னார், “ஒரே மொழியில் இருக்க மறுக்கும் ஒரு கதை.” வணிகர் சிரித்தார், பிறகு அமைதியானார்—தாளிலிருந்து பாட்டியின் குரல் எழுந்தது, அருகில் அமர்ந்திருப்பது போல.',
            'அவர்கள் புத்தகத்தை நகரம் முழுவதும் எடுத்துச் சென்றனர். தேநீர் கடையில் ஒரு மாணவர் அறிந்த வணக்கத்தைக் கேட்டு சிரித்தார். நிலையத்தில் ஒரு பயணி கண்களை மூடிக் கேட்டார். பூங்காவில் ஒரு முதியவர் நூருக்கு முன் வாக்கியத்தை முடித்தார், ஏனெனில் கதை ஏற்கனவே அவரது நினைவில் வாழ்ந்தது.',
            'மாலையில் கடைசிப் பக்கம் ஏறக்குறைய வெறுமையாக இருந்தது. ஒரு வரி மட்டும் இருந்தது: நீங்கள் நேசிக்கும் மொழியில் அடுத்த பக்கத்தை எழுதுங்கள். நூர் மெதுவாக எழுதினார். மையில் மழை வாசனை. புத்தகத்தை மூடியதும் ஆறு ஆயிரம் குரல்கள் போல் ஒலித்தது, எல்லோரும் கேட்க ஒப்புக்கொண்டது போல.',
            'அன்று இரவு சந்தை விளக்குகள் இருளில் நிறுத்தற்குறிகள் போல் தெரிந்தன. நூர் ஒரு எளிய பெரிய உண்மையை உணர்ந்தார்: சொற்கள் முடிந்ததும் கதை முடிவதில்லை. வேறு ஒருவர் அதைக் கேட்டு பதில் சொல்ல முடியும் போதுதான் கதை முழுமையாகிறது.',
        ],
    ],
    [
        'id' => 'te',
        'name' => 'Telugu',
        'native' => 'తెలుగు',
        'dir' => 'ltr',
        'font' => 'Noto Sans Telugu',
        'title' => 'నది ఒడ్డున దొరికిన పుస్తకం',
        'paragraphs' => [
            'ఒక నిశ్శబ్ద ఉదయం నూర్ అనే పిల్లవాడు పాత మార్కెట్ వెనుక నది ఒడ్డున నడిచాడు. నీరు నెమ్మదిగా కదిలింది. రెండు తడి రాళ్ల మధ్య పేరులేని పుస్తకం దొరికింది. మొదటి పేజీ తెరిచినప్పుడు అది వారి భాషలో మాట్లాడింది. తర్వాతి పేజీ మారింది.',
            'నూర్ మామిడి చెట్టు కింద కూర్చుని చదివాడు. ఒక వ్యాపారి ఏం చదువుతున్నారని అడిగాడు. నూర్ అన్నాడు, ఇది ఒక భాషలో ఉండటానికి నిరాకరించే కథ. కాగితం నుంచి అమ్మమ్మ స్వరం లేచింది.',
            'వారు పుస్తకాన్ని నగరం అంతా తీసుకెళ్లారు. టీ దుకాణంలో ఒక విద్యార్థి నమస్కారం విని నవ్వాడు. స్టేషన్లో ఒక యాత్రికుడు కళ్లు మూసుకుని విన్నాడు. పార్కులో ఒక వృద్ధురాలు నూర్ కంటే ముందు వాక్యం పూర్తి చేసింది.',
            'సాయంత్రానికి చివరి పేజీ దాదాపు ఖాళీగా ఉంది. ఒక వాక్యం మాత్రమే మిగిలింది. నువ్వు ప్రేమించే భాషలో తర్వాతి పేజీ రాయి. నూర్ నెమ్మదిగా రాశాడు. పుస్తకం మూసినప్పుడు నది వేల గళాల్లా వినిపించింది.',
            'ఆ రాత్రి మార్కెట్ దీపాలు చీకటిపై విరామ చిహ్నాల్లా కనిపించాయి. నూర్ ఒక సరళమైన సత్యం అర్థం చేసుకున్నాడు. పదాలు అయిపోతే కథ అయిపోదు. ఇంకొకరు దాన్ని విని సమాధానం చెప్పగలిగినప్పుడే కథ పూర్తవుతుంది.',
        ],
    ],
    [
        'id' => 'ml',
        'name' => 'Malayalam',
        'native' => 'മലയാളം',
        'dir' => 'ltr',
        'font' => 'Noto Sans Malayalam',
        'title' => 'നദിക്കരയിൽ കിട്ടിയ പുസ്തകം',
        'paragraphs' => [
            'ഒരു നിശബ്ദ പ്രഭാതത്തിൽ നൂർ എന്ന കുട്ടി പഴയ ചന്തയുടെ പിന്നിലുള്ള നദിക്കരയിലൂടെ നടന്നു. വെള്ളം പതുക്കെ ഒഴുകി. രണ്ട് നനഞ്ഞ കല്ലുകൾക്കിടയിൽ പേരില്ലാത്ത ഒരു പുസ്തകം കിട്ടി. ആദ്യ പേജ് തുറന്നപ്പോൾ അത് അവരുടെ ഭാഷയിൽ സംസാരിച്ചു. അടുത്ത പേജ് മാറി.',
            'നൂർ മാവിന്റെ കീഴിൽ ഇരുന്നു വായിച്ചു. ഒരു വ്യാപാരി എന്താണ് വായിക്കുന്നതെന്ന് ചോദിച്ചു. നൂർ പറഞ്ഞു, ഒരു ഭാഷയിൽ നിൽക്കാൻ വിസമ്മതിക്കുന്ന ഒരു കഥ. കടലാസിൽ നിന്ന് മുത്തശ്ശിയുടെ ശബ്ദം ഉയർന്നു.',
            'അവർ പുസ്തകം നഗരത്തിലൂടെ കൊണ്ടുപോയി. ചായക്കടയിൽ ഒരു വിദ്യാർത്ഥി പുഞ്ചിരിച്ചു. സ്റ്റേഷനിൽ ഒരു യാത്രക്കാരൻ കണ്ണടച്ച് കേട്ടു. പാർക്കിൽ ഒരു വൃദ്ധ നൂറിന് മുമ്പ് വാക്യം പൂർത്തിയാക്കി.',
            'വൈകുന്നേരമായപ്പോൾ അവസാന പേജ് ഏകദേശം ശൂന്യമായിരുന്നു. ഒരു വരി മാത്രം. നീ സ്നേഹിക്കുന്ന ഭാഷയിൽ അടുത്ത പേജ് എഴുതുക. നൂർ പതുക്കെ എഴുതി. പുസ്തകം അടച്ചപ്പോൾ നദി ആയിരം ശബ്ദങ്ങളെപ്പോലെ കേട്ടു.',
            'ആ രാത്രി ചന്തയിലെ വിളക്കുകൾ ഇരുട്ടിൽ വിരാമചിഹ്നങ്ങൾ പോലെ തോന്നി. നൂർ ഒരു ലളിതവും വലുതുമായ കാര്യം മനസ്സിലാക്കി. വാക്കുകൾ തീരുമ്പോൾ കഥ തീരുന്നില്ല. മറ്റൊരാൾക്ക് അത് കേട്ട് മറുപടി പറയാൻ കഴിയുമ്പോഴാണ് കഥ പൂർത്തിയാകുന്നത്.',
        ],
    ],
    [
        'id' => 'gu',
        'name' => 'Gujarati',
        'native' => 'ગુજરાતી',
        'dir' => 'ltr',
        'font' => 'Noto Sans Gujarati',
        'title' => 'નદી કિનારે મળેલું પુસ્તક',
        'paragraphs' => [
            'એક શાંત સવારે નૂર નામનું બાળક જૂના બજાર પાછળ નદી કિનારે ચાલતું હતું. પાણી ધીમે વહેતું હતું. બે ભીના પથ્થર વચ્ચે એક પુસ્તક મળ્યું જેના કવર પર શીર્ષક નહોતું. પહેલું પાનું ખૂલ્યું તો તે તેમની ભાષામાં બોલ્યું. આગલું પાનું બદલાયું.',
            'નૂર કેરીના ઝાડ નીચે બેસીને વાંચ્યું. એક વેપારીએ પૂછ્યું કે શું વાંચો છો. નૂરે કહ્યું, એવી વાર્તા જે એક ભાષામાં રહેવા માગતી નથી. વેપારી હસ્યો. પછી કાગળમાંથી દાદીનો અવાજ ઊઠ્યો.',
            'તેઓ પુસ્તક લઈને શહેર ફર્યા. ચાની દુકાનમાં એક વિદ્યાર્થીએ સ્મિત કર્યું. સ્ટેશન પર એક મુસાફરે આંખો બંધ કરી. પાર્કમાં એક વૃદ્ધાએ નૂરથી પહેલાં વાક્ય પૂરું કર્યું.',
            'સાંજ સુધી છેલ્લું પાનું લગભગ ખાલી હતું. માત્ર એક લીટી બચી. જે ભાષા તું ચાહે છે તેમાં આગલું પાનું લખ. નૂરે ધીમે લખ્યું. પુસ્તક બંધ કરતાં નદી હજાર અવાજો જેવી લાગી.',
            'તે રાત્રે બજારના દીવા અંધકાર પર વિરામચિહ્નો જેવા દેખાયા. નૂરે એક સાદી વાત સમજી. શબ્દો પૂરા થાય ત્યારે વાર્તા પૂરી થતી નથી. બીજો કોઈ સાંભળીને જવાબ આપે ત્યારે વાર્તા પૂરી થાય છે.',
        ],
    ],
    [
        'id' => 'pa',
        'name' => 'Punjabi',
        'native' => 'ਪੰਜਾਬੀ',
        'dir' => 'ltr',
        'font' => 'Noto Sans Gurmukhi',
        'title' => 'ਨਦੀ ਕੰਢੇ ਮਿਲੀ ਕਿਤਾਬ',
        'paragraphs' => [
            'ਇੱਕ ਸ਼ਾਂਤ ਸਵੇਰ ਨੂਰ ਨਾਂ ਦਾ ਬੱਚਾ ਪੁਰਾਣੇ ਬਾਜ਼ਾਰ ਪਿੱਛੇ ਨਦੀ ਕੰਢੇ ਤੁਰ ਰਿਹਾ ਸੀ. ਪਾਣੀ ਹੌਲੀ ਵਗਦਾ ਸੀ. ਦੋ ਗਿੱਲੇ ਪੱਥਰਾਂ ਵਿਚਕਾਰ ਇੱਕ ਕਿਤਾਬ ਮਿਲੀ ਜਿਸ ਦੇ ਕਵਰ ਤੇ ਸਿਰਲੇਖ ਨਹੀਂ ਸੀ. ਪਹਿਲਾ ਪੰਨਾ ਖੁਲਿਆ ਤਾਂ ਉਹ ਉਨ੍ਹਾਂ ਦੀ ਭਾਸ਼ਾ ਵਿਚ ਬੋਲੀ. ਅਗਲਾ ਪੰਨਾ ਬਦਲ ਗਿਆ.',
            'ਨੂਰ ਅੰਬ ਦੇ ਰੁੱਖ ਹੇਠ ਬੈਠ ਕੇ ਪੜ੍ਹਦਾ ਰਿਹਾ. ਇੱਕ ਵਪਾਰੀ ਨੇ ਪੁੱਛਿਆ ਉਹ ਕੀ ਪੜ੍ਹ ਰਹੇ ਹਨ. ਨੂਰ ਨੇ ਕਿਹਾ, ਇੱਕ ਐਸੀ ਕਹਾਣੀ ਜੋ ਇੱਕ ਭਾਸ਼ਾ ਵਿਚ ਰਹਿਣਾ ਨਹੀਂ ਚਾਹੁੰਦੀ. ਵਪਾਰੀ ਹੱਸਿਆ. ਫਿਰ ਕਾਗਜ਼ ਤੋਂ ਦਾਦੀ ਦੀ ਆਵਾਜ਼ ਉੱਠੀ.',
            'ਉਹ ਕਿਤਾਬ ਲੈ ਕੇ ਸ਼ਹਿਰ ਘੁੰਮੇ. ਚਾਹ ਦੀ ਹੱਟੀ ਵਿਚ ਇੱਕ ਵਿਦਿਆਰਥੀ ਮੁਸਕਰਾਇਆ. ਸਟੇਸ਼ਨ ਤੇ ਇੱਕ ਯਾਤਰੀ ਨੇ ਅੱਖਾਂ ਬੰਦ ਕਰ ਲਈਆਂ. ਪਾਰਕ ਵਿਚ ਇੱਕ ਬਜ਼ੁਰਗ ਔਰਤ ਨੇ ਨੂਰ ਤੋਂ ਪਹਿਲਾਂ ਵਾਕ ਪੂਰਾ ਕਰ ਦਿੱਤਾ.',
            'ਸ਼ਾਮ ਤੱਕ ਆਖਰੀ ਪੰਨਾ ਲਗਭਗ ਖਾਲੀ ਸੀ. ਸਿਰਫ਼ ਇੱਕ ਲਾਈਨ ਬਚੀ. ਜਿਸ ਭਾਸ਼ਾ ਨੂੰ ਤੂੰ ਪਿਆਰ ਕਰਦਾ ਹੈਂ ਉਸ ਵਿਚ ਅਗਲਾ ਪੰਨਾ ਲਿਖ. ਨੂਰ ਨੇ ਹੌਲੀ ਲਿਖਿਆ. ਕਿਤਾਬ ਬੰਦ ਕਰਦਿਆਂ ਨਦੀ ਹਜ਼ਾਰਾਂ ਆਵਾਜ਼ਾਂ ਵਾਂਗ ਲੱਗੀ.',
            'ਉਸ ਰਾਤ ਬਾਜ਼ਾਰ ਦੀਆਂ ਲਾਈਟਾਂ ਹਨੇਰੇ ਉੱਤੇ ਵਿਰਾਮ ਚਿੰਨ੍ਹਾਂ ਵਾਂਗ ਦਿਸੀਆਂ. ਨੂਰ ਨੇ ਇੱਕ ਸਾਦੀ ਗੱਲ ਸਮਝੀ. ਸ਼ਬਦ ਖਤਮ ਹੋਣ ਨਾਲ ਕਹਾਣੀ ਖਤਮ ਨਹੀਂ ਹੁੰਦੀ. ਕਹਾਣੀ ਤਦ ਪੂਰੀ ਹੁੰਦੀ ਹੈ ਜਦੋਂ ਕੋਈ ਹੋਰ ਉਸ ਨੂੰ ਸੁਣ ਸਕੇ ਤੇ ਜਵਾਬ ਦੇ ਸਕੇ.',
        ],
    ],
    [
        'id' => 'kn',
        'name' => 'Kannada',
        'native' => 'ಕನ್ನಡ',
        'dir' => 'ltr',
        'font' => 'Noto Sans Kannada',
        'title' => 'ನದಿ ದಡದಲ್ಲಿ ಸಿಕ್ಕ ಪುಸ್ತಕ',
        'paragraphs' => [
            'ಒಂದು ನಿಶ್ಶಬ್ದ ಬೆಳಗ್ಗೆ ನೂರ್ ಎಂಬ ಮಗು ಹಳೆಯ ಮಾರುಕಟ್ಟೆಯ ಹಿಂದೆ ನದಿ ದಡದಲ್ಲಿ ನಡೆಯಿತು. ನೀರು ನಿಧಾನವಾಗಿ ಹರಿಯುತ್ತಿತ್ತು. ಎರಡು ಒದ್ದೆ ಕಲ್ಲುಗಳ ನಡುವೆ ಹೆಸರಿಲ್ಲದ ಪುಸ್ತಕ ಸಿಕ್ಕಿತು. ಮೊದಲ ಪುಟ ತೆರೆದಾಗ ಅದು ಅವರ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿತು. ಮುಂದಿನ ಪುಟ ಬದಲಾಯಿತು.',
            'ನೂರ್ ಮಾವಿನ ಮರದ ಕೆಳಗೆ ಕುಳಿತು ಓದಿದ. ಒಬ್ಬ ವ್ಯಾಪಾರಿ ಏನು ಓದುತ್ತಿದ್ದೀರಿ ಎಂದು ಕೇಳಿದ. ನೂರ್ ಹೇಳಿದ, ಇದು ಒಂದು ಭಾಷೆಯಲ್ಲಿ ಇರಲು ನಿರಾಕರಿಸುವ ಕಥೆ. ವ್ಯಾಪಾರಿ ನಕ್ಕ. ನಂತರ ಕಾಗದದಿಂದ ಅಜ್ಜಿಯ ಧ್ವನಿ ಏಳಿತು.',
            'ಅವರು ಪುಸ್ತಕವನ್ನು ನಗರದಾದ್ಯಂತ ತೆಗೆದುಕೊಂಡು ಹೋದರು. ಟೀ ಅಂಗಡಿಯಲ್ಲಿ ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿ ನಕ್ಕ. ನಿಲ್ದಾಣದಲ್ಲಿ ಒಬ್ಬ ಪ್ರಯಾಣಿಕ ಕಣ್ಣು ಮುಚ್ಚಿ ಕೇಳಿದ. ಉದ್ಯಾನದಲ್ಲಿ ಒಬ್ಬ ವೃದ್ಧೆ ನೂರ್ಗಿಂತ ಮೊದಲು ವಾಕ್ಯ ಮುಗಿಸಿದಳು.',
            'ಸಂಜೆಯ ವೇಳೆಗೆ ಕೊನೆಯ ಪುಟ ಬಹುತೇಕ ಖಾಲಿಯಾಗಿತ್ತು. ಒಂದು ಸಾಲು ಮಾತ್ರ ಉಳಿದಿತ್ತು. ನೀನು ಪ್ರೀತಿಸುವ ಭಾಷೆಯಲ್ಲಿ ಮುಂದಿನ ಪುಟ ಬರೆ. ನೂರ್ ನಿಧಾನವಾಗಿ ಬರೆದ. ಪುಸ್ತಕ ಮುಚ್ಚಿದಾಗ ನದಿ ಸಾವಿರ ಧ್ವನಿಗಳಂತೆ ಕೇಳಿಸಿತು.',
            'ಆ ರಾತ್ರಿ ಮಾರುಕಟ್ಟೆಯ ದೀಪಗಳು ಕತ್ತಲೆಯ ಮೇಲೆ ವಿರಾಮ ಚಿಹ್ನೆಗಳಂತೆ ಕಾಣಿಸಿದವು. ನೂರ್ ಒಂದು ಸರಳ ಸತ್ಯವನ್ನು ಅರಿತ. ಪದಗಳು ಮುಗಿದಾಗ ಕಥೆ ಮುಗಿಯುವುದಿಲ್ಲ. ಇನ್ನೊಬ್ಬರು ಕೇಳಿ ಉತ್ತರಿಸಬಹುದಾದಾಗಲೇ ಕಥೆ ಪೂರ್ಣವಾಗುತ್ತದೆ.',
        ],
    ],
    [
        'id' => 'mr',
        'name' => 'Marathi',
        'native' => 'मराठी',
        'dir' => 'ltr',
        'font' => 'Noto Sans Devanagari',
        'title' => 'नदीकाठी सापडलेले पुस्तक',
        'paragraphs' => [
            'एक शांत सकाळी नूर नावाचे मूल जुन्या बाजारामागे नदीकाठी चालत होते. पाणी हळू वाहत होते, जणू विचार करत असावे. दोन ओल्या दगडांमध्ये एक पुस्तक सापडले, ज्याच्या मुखपृष्ठावर शीर्षक नव्हते. पहिले पान उघडले तर ते त्यांच्या भाषेत बोलले. पुढचे पान बदलले. अक्षरे पक्ष्यांसारखी नवीन झाड शोधत सरकली.',
            'नूर आंब्याच्या झाडाखाली बसून वाचत राहिले, जोपर्यंत सूर्य डोक्यावर आला. मसाल्याच्या गल्लीतील एक व्यापारी विचारले ते काय वाचताय. नूर म्हणाले, “अशी गोष्ट जी एका भाषेत राहू इच्छित नाही.” व्यापारी हसला, मग शांत झाला—कागदातून त्याच्या आजीचा आवाज उठला, जणू ती बाजूलाच बसली आहे.',
            'ते पुस्तक घेऊन शहर फिरले. चहाच्या दुकानात एक विद्यार्थी ओळखीचे अभिवादन ऐकून हसला. स्टेशनवर एक प्रवासी डोळे मिटून ऐकू लागला. बागेत एक वृद्धाईनं नूरच्या आधी वाक्य पूर्ण केले, कारण गोष्ट आधीच तिच्या आठवणीत राहत होती.',
            'संध्याकाळी शेवटचे पान जवळजवळ रिकामे होते. फक्त एक ओळ उरली: तुम्ही ज्या भाषेवर प्रेम करता त्यात पुढचे पान लिहा. नूर हळू लिहिले. शाईत पावसाचा वास होता. पुस्तक बंद करताच नदी हजारो आवाजांसारखी वाटू लागली, जणू सगळे ऐकायला तयार आहेत.',
            'त्या रात्री बाजारातील दिवे अंधारात विरामचिन्हांसारखे दिसले. नूरला एक साधी आणि मोठी गोष्ट कळली: शब्द संपले की गोष्ट संपत नाही. गोष्ट तेव्हा पूर्ण होते जेव्हा दुसरा कोणी ती ऐकू शकतो आणि उत्तर देऊ शकतो.',
        ],
    ],
    [
        'id' => 'ne',
        'name' => 'Nepali',
        'native' => 'नेपाली',
        'dir' => 'ltr',
        'font' => 'Noto Sans Devanagari',
        'title' => 'नदी किनारमा भेटिएको किताब',
        'paragraphs' => [
            'एक शान्त बिहान नूर नामको बालक पुरानो बजार पछाडि नदी किनार हिँडिरहेको थियो। पानी बिस्तारै बगिरहेको थियो, जस्तो सोचिरहेको होस्। दुई भिजेका ढुङ्गाबीच एउटा किताब भेटियो, जसको आवरणमा कुनै शीर्षक थिएन। पहिलो पृष्ठ खुल्यो भने त्यो उनीहरूकै भाषामा बोल्यो। अर्को पृष्ठ बदलियो। अक्षरहरू चराझैँ नयाँ रूख खोज्दै सर्न थाले।',
            'नूर आँपको रूखमुनि बसेर पढिरह्यो, जबसम्म घाम टाउकोमा आएन। मसला गल्लीका एक व्यापारीले सोधे के पढ्दै हुनुहुन्छ। नूरले भन्यो, “एउटा यस्तो कथा जुन एउटा भाषामा बस्न चाहँदैन।” व्यापारी हाँसे, अनि चुप भए—कागजबाट हजुरआमाको आवाज उठ्यो, जस्तो उहाँ छेउमै बस्नुभएको होस्।',
            'उनीहरू किताब लिएर सहर घुमे। चिया पसलमा एक विद्यार्थीले चिनेको अभिवादन सुनेर मुस्कुराए। स्टेशनमा एक यात्रीले आँखा चिम्लेर सुने। पार्कमा एक वृद्धाले नूरभन्दा पहिले वाक्य पूरा गरिन्, किनकि कथा पहिले नै उनको स्मृतिमा बस्थ्यो।',
            'साँझसम्म अन्तिम पृष्ठ लगभग खाली थियो। एउटा मात्र हरफ बाँकी थियो: तिमीले माया गर्ने भाषामा अर्को पृष्ठ लेख। नूरले बिस्तारै लेख्यो। मसीमा वर्षाको गन्ध थियो। किताब बन्द गर्दा नदी हजारौँ स्वरजस्तो सुनियो, जस्तो सबै सुन्न तयार छन्।',
            'त्यस रात बजारका बत्तीहरू अँध्यारोमा विराम चिन्हजस्ता देखिए। नूरले एउटा सरल र ठूलो कुरा बुझ्यो: शब्द सकिएपछि कथा सकिँदैन। कथा तब पूरा हुन्छ जब अर्को मान्छेले त्यो सुन्न र जवाफ दिन सक्छ।',
        ],
    ],
    [
        'id' => 'zh',
        'name' => 'Chinese',
        'native' => '中文',
        'dir' => 'ltr',
        'font' => 'Noto Sans CJK SC',
        'title' => '河边的书',
        'paragraphs' => [
            '一个安静的早晨，名叫努尔的孩子沿着旧市场后面的河边走着。水走得很慢，像在思考。两块湿石头中间，他们找到一本封面没有书名的书。第一页打开时，它用他们自己的语言说话。下一页变了。字像寻找新树的鸟儿一样重新排列。',
            '努尔坐在芒果树下读到太阳升到头顶。香料巷的商人问他们在读什么。努尔说：“一个不肯只留在一种语言里的故事。”商人笑了，随后安静下来——纸上浮起祖母的声音，仿佛她就坐在旁边。',
            '他们带着书走过城市。茶摊上，一个学生听见熟悉的问候，笑了。车站里，一位旅客闭上眼睛听着。公园里，一位老人比努尔更早说完那句话，因为故事早已住在她的记忆里。',
            '傍晚，最后一页几乎是空白。只剩一行：用你热爱的语言写下下一页。努尔写得很慢。墨水有雨后的气味。合上书时，河水听起来像千万个声音同意去倾听。',
            '那天夜里，市场的灯像标点落在黑暗上。努尔明白一件简单又巨大的事：字结束了，故事并没有结束。当另一个人听得见、答得上，故事才算完成。',
        ],
    ],
    [
        'id' => 'ja',
        'name' => 'Japanese',
        'native' => '日本語',
        'dir' => 'ltr',
        'font' => 'Noto Sans CJK JP',
        'title' => '川べりの本',
        'paragraphs' => [
            '静かな朝、ヌールという子どもは古い市場の裏の川沿いを歩いていた。水は考えるようにゆっくり流れていた。濡れた石のあいだに、表紙に題名のない本を見つけた。最初のページを開くと、それは自分たちの言葉で語り始めた。次のページは変わった。文字は新しい木を探す鳥のように並び直した。',
            'ヌールはマンゴーの木の下に座り、太陽が頭の上に来るまで読んだ。香辛料の路地の商人が何を読んでいるのか尋ねた。ヌールは言った。「一つの言葉の中に留まることを拒む物語です。」商人は笑い、それから黙った。紙から祖母の声が立ち上がり、隣に座っているようだった。',
            '彼らは本を抱えて街を歩いた。茶店では学生が聞き慣れた挨拶を聞いて微笑んだ。駅では旅人が目を閉じて耳を澄ませた。公園では老女がヌールより先に文を終えた。物語はすでに彼女の記憶の中に住んでいたからだ。',
            '夕方、最後のページはほとんど空白だった。一行だけ残っていた。あなたが愛する言葉で次のページを書きなさい。ヌールはゆっくり書いた。インクは熱のあとの雨の匂いがした。本を閉じると、川は耳を傾けることに同意した何千もの声のように聞こえた。',
            'その夜、市場の明かりは闇の上の句読点のようだった。ヌールは単純で大きなことを理解した。言葉が終わっても物語は終わらない。ほかの誰かがそれを聞き、答えられるとき、物語は終わる。',
        ],
    ],
    [
        'id' => 'ko',
        'name' => 'Korean',
        'native' => '한국어',
        'dir' => 'ltr',
        'font' => 'Noto Sans CJK KR',
        'title' => '강가에서 찾은 책',
        'paragraphs' => [
            '고요한 아침, 누르라는 아이가 오래된 시장 뒤 강가를 걸었다. 물은 생각하듯 천천히 흘렀다. 젖은 돌 두 개 사이에서 표지에 제목이 없는 책을 찾았다. 첫 장을 열자 책은 그들의 말로 이야기했다. 다음 장은 바뀌었다. 글자들은 새 나무를 찾는 새처럼 자리를 옮겼다.',
            '누르는 망고나무 아래 앉아 해가 머리 위에 올 때까지 읽었다. 향신료 골목의 상인이 무엇을 읽느냐고 물었다. 누르가 말했다. “한 언어 안에만 머물기를 거부하는 이야기예요.” 상인은 웃다가 조용해졌다. 종이에서 할머니의 목소리가 올라와, 곁에 앉아 있는 듯했다.',
            '그들은 책을 들고 도시를 걸었다. 찻집에서 학생이 익숙한 인사를 듣고 미소 지었다. 역에서 여행자가 눈을 감고 들었다. 공원에서 한 할머니가 누르보다 먼저 문장을 끝냈다. 이야기가 이미 그분의 기억 속에 살고 있었기 때문이다.',
            '저녁이 되자 마지막 장은 거의 비어 있었다. 한 줄만 남았다. 네가 사랑하는 언어로 다음 장을 써라. 누르는 천천히 썼다. 잉크에서는 더위 뒤에 온 빗내음이 났다. 책을 덮자 강은 듣기로 동의한 수천 개의 목소리처럼 들렸다.',
            '그날 밤 시장 불빛은 어둠 위의 문장 부호 같았다. 누르는 단순하고 큰 것을 알았다. 말이 끝난다고 이야기가 끝나지 않는다. 다른 사람이 듣고 대답할 수 있을 때 이야기는 끝난다.',
        ],
    ],
];
